const roomSeed = [
  {
    roomNumber: '101',
    name: 'Aurora 101',
    type: 'Single',
    capacity: 1,
    price: 40,
    isAvailable: true,
    amenities: ['AC', 'WiFi', 'Study Desk'],
    photoUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
    description: 'Calm single room with natural light and minimalist decor.',
    rating: 4.8,
  },
  {
    roomNumber: '202',
    name: 'Lumen 202',
    type: 'Double',
    capacity: 2,
    price: 65,
    isAvailable: true,
    amenities: ['WiFi', 'Balcony', 'Wardrobe'],
    photoUrl: 'https://images.unsplash.com/photo-1560067174-c5a3a8f37060?auto=format&fit=crop&w=800&q=80',
    description: 'Spacious double room ideal for roommates who value comfort.',
    rating: 4.6,
  },
  {
    roomNumber: '303',
    name: 'Velvet 303',
    type: 'Suite',
    capacity: 3,
    price: 95,
    isAvailable: true,
    amenities: ['AC', 'WiFi', 'Mini Fridge', 'Private Bath'],
    photoUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
    description: 'Suite with lounge area and warm earthy palette for long stays.',
    rating: 4.9,
  },
  {
    roomNumber: '102',
    name: 'Oasis 102',
    type: 'Single',
    capacity: 1,
    price: 45,
    isAvailable: true,
    amenities: ['AC', 'WiFi', 'Study Desk', 'Ergonomic Chair'],
    photoUrl: 'https://images.unsplash.com/photo-1598928506311-c55dd12cb071?auto=format&fit=crop&w=800&q=80',
    description: 'A serene sanctuary featuring a highly ergonomic setup for focused study.',
    rating: 4.7,
  },
  {
    roomNumber: '201',
    name: 'Zenith 201',
    type: 'Double',
    capacity: 2,
    price: 70,
    isAvailable: true,
    amenities: ['WiFi', 'Balcony', 'Wardrobe', 'Coffee Maker'],
    photoUrl: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80',
    description: 'Bright and airy double room with a modern coffee station.',
    rating: 4.8,
  },
  {
    roomNumber: '301',
    name: 'Summit 301',
    type: 'Suite',
    capacity: 3,
    price: 110,
    isAvailable: true,
    amenities: ['AC', 'WiFi', 'Mini Fridge', 'Private Bath', 'Lounge'],
    photoUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    description: 'Our top-floor premium suite featuring expansive lounge seating.',
    rating: 5.0,
  },
  {
    roomNumber: '103',
    name: 'Nova 103',
    type: 'Single',
    capacity: 1,
    price: 42,
    isAvailable: true,
    amenities: ['WiFi', 'Study Desk', 'Bookshelf'],
    photoUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
    description: 'Compact and extremely efficient minimalist room layout.',
    rating: 4.5,
  },
  {
    roomNumber: '203',
    name: 'Ember 203',
    type: 'Double',
    capacity: 2,
    price: 68,
    isAvailable: true,
    amenities: ['AC', 'WiFi', 'Wardrobe', 'Smart TV'],
    photoUrl: 'https://m.media-amazon.com/images/I/61auXI5JPKL._AC_UF894,1000_QL80_.jpg',
    description: 'Cozy collaborative space optimized for relaxation and media viewing.',
    rating: 4.7,
  },
  {
    roomNumber: '302',
    name: 'Haven 302',
    type: 'Suite',
    capacity: 4,
    price: 130,
    isAvailable: true,
    amenities: ['AC', 'WiFi', 'Kitchenette', 'Private Bath', 'Lounge'],
    photoUrl: 'https://images.unsplash.com/photo-1555636222-cae831e670b3?auto=format&fit=crop&w=800&q=80',
    description: 'The ultimate group suite equipped with a kitchenette for maximum independence.',
    rating: 4.9,
  }
];

const userSeed = [
  {
    name: 'Admin User',
    email: 'admin@hostelbloom.com',
    password: 'Admin@123',
    role: 'admin',
  },
];

module.exports = { roomSeed, userSeed };
